
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 25;
  public static final int OVER = 16;
  public static final int LTEQ = 24;
  public static final int UMINUS = 38;
  public static final int LPAREN = 17;
  public static final int SEMI = 19;
  public static final int INT = 4;
  public static final int MINUS = 14;
  public static final int TILDE = 28;
  public static final int RPAREN = 18;
  public static final int AND = 30;
  public static final int LT = 11;
  public static final int OR = 29;
  public static final int BOOL = 35;
  public static final int COMMA = 31;
  public static final int NUM = 34;
  public static final int PLUS = 13;
  public static final int IF = 2;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int VOID = 6;
  public static final int EQ = 10;
  public static final int ERROR = 39;
  public static final int COM = 33;
  public static final int LBRACK = 22;
  public static final int TRUTH = 36;
  public static final int TIMES = 15;
  public static final int EQT = 26;
  public static final int NEQT = 27;
  public static final int LBRACE = 20;
  public static final int ELSE = 3;
  public static final int RBRACK = 23;
  public static final int String = 37;
  public static final int WHILE = 7;
  public static final int RBRACE = 21;
  public static final int FALSE = 8;
  public static final int GT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "INT",
  "RETURN",
  "VOID",
  "WHILE",
  "FALSE",
  "TRUE",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "LTEQ",
  "GTEQ",
  "EQT",
  "NEQT",
  "TILDE",
  "OR",
  "AND",
  "COMMA",
  "ID",
  "COM",
  "NUM",
  "BOOL",
  "TRUTH",
  "String",
  "UMINUS",
  "ERROR"
  };
}

